# Generated by Django 5.0.2 on 2024-02-21 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bod_stav',
            fields=[
                ('id_bod_stav', models.IntegerField(primary_key=True, serialize=False)),
                ('popis', models.TextField()),
            ],
            options={
                'verbose_name': 'Stav bodu',
                'verbose_name_plural': 'Stavy bodu',
                'db_table': 'bod_stav',
            },
        ),
        migrations.CreateModel(
            name='druh_bodu',
            fields=[
                ('id_bodu', models.IntegerField(primary_key=True, serialize=False)),
                ('popis', models.TextField()),
            ],
            options={
                'verbose_name': 'Druh bodu',
                'verbose_name_plural': 'Druhy bodu',
                'db_table': 'druh_bodu',
            },
        ),
        migrations.CreateModel(
            name='DruhTisku',
            fields=[
                ('id_druh', models.IntegerField(primary_key=True, serialize=False)),
                ('druh_t', models.TextField()),
                ('nazev_druh', models.TextField()),
            ],
            options={
                'verbose_name': 'Druh tisku',
                'verbose_name_plural': 'Druhy tisků',
                'db_table': 'druh_tisku',
            },
        ),
        migrations.CreateModel(
            name='Hist',
            fields=[
                ('id_hist', models.IntegerField(primary_key=True, serialize=False)),
                ('id_tisk', models.IntegerField()),
                ('datum', models.TextField()),
                ('id_hlas', models.IntegerField()),
                ('id_prechod', models.IntegerField()),
                ('id_bod', models.IntegerField()),
                ('schuze', models.IntegerField()),
                ('usnes_ps', models.IntegerField()),
                ('orgv_id_posl', models.IntegerField()),
                ('ps_id_posl', models.IntegerField()),
                ('orgv_p_usn', models.IntegerField()),
                ('zaver_publik', models.TextField()),
                ('zaver_sb_castka', models.IntegerField()),
                ('zaver_sb_cislo', models.IntegerField()),
                ('poznamka', models.TextField()),
            ],
            options={
                'verbose_name': 'Historie',
                'verbose_name_plural': 'Historie',
                'db_table': 'hist',
            },
        ),
        migrations.CreateModel(
            name='HistVybory',
            fields=[
                ('id_tisku', models.IntegerField(primary_key=True, serialize=False)),
                ('id_organ', models.IntegerField()),
                ('typ', models.IntegerField()),
                ('id_hist', models.IntegerField()),
                ('id_posl', models.IntegerField()),
                ('poradi', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Historie výborů',
                'verbose_name_plural': 'Historie výborů',
                'db_table': 'hist_vybory',
            },
        ),
        migrations.CreateModel(
            name='hl_hlasovani',
            fields=[
                ('id_hlasovani', models.IntegerField(primary_key=True, serialize=False)),
                ('schuze', models.IntegerField()),
                ('cislo', models.IntegerField()),
                ('bod', models.IntegerField(null=True)),
                ('datum', models.DateField()),
                ('cas', models.TimeField()),
                ('pro', models.IntegerField()),
                ('proti', models.IntegerField()),
                ('zdrzel', models.IntegerField()),
                ('nehlasoval', models.IntegerField(null=True)),
                ('prihlaseno', models.IntegerField()),
                ('kvorum', models.IntegerField()),
                ('druh_hlasovani', models.CharField(choices=[('N', 'Normální'), ('R', 'Ruční'), ('E', 'Technická závada')], max_length=1)),
                ('vysledek', models.CharField(choices=[('A', 'Přijato'), ('R', 'Zamítnuto'), ('X', 'Výsledek neznámý'), ('Q', 'Výsledek neznámý u neveřejného hlasování'), ('K', 'Nedosaženo kvóra')], max_length=1)),
                ('nazev_dlouhy', models.TextField(null=True)),
                ('nazev_kratky', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Hlasování',
                'verbose_name_plural': 'Hlasování',
                'db_table': 'hl_hlasovani',
            },
        ),
        migrations.CreateModel(
            name='NavrhPodpis',
            fields=[
                ('id_tisk', models.IntegerField(primary_key=True, serialize=False)),
                ('id_osoba', models.IntegerField()),
                ('stav', models.IntegerField()),
                ('datum', models.DateField()),
            ],
            options={
                'verbose_name': 'Návrh podpisu',
                'verbose_name_plural': 'Návrhy podpisů',
                'db_table': 'navrh_podpis',
            },
        ),
        migrations.CreateModel(
            name='Osoby',
            fields=[
                ('id_osoba', models.AutoField(primary_key=True, serialize=False)),
                ('pred', models.TextField(null=True)),
                ('jmeno', models.TextField(null=True)),
                ('prijmeni', models.TextField(null=True)),
                ('za', models.TextField(null=True)),
                ('narozeni', models.DateField(null=True)),
                ('pohlavi', models.CharField(max_length=1, null=True)),
                ('zmena', models.DateField(null=True)),
                ('umrti', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Osoba',
                'verbose_name_plural': 'Osoby',
                'db_table': 'osoby',
            },
        ),
        migrations.CreateModel(
            name='Prechody',
            fields=[
                ('id_prechod', models.IntegerField(primary_key=True, serialize=False)),
                ('odkud', models.IntegerField()),
                ('kam', models.IntegerField()),
                ('id_akce', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Přechod',
                'verbose_name_plural': 'Přechody',
                'db_table': 'prechody',
            },
        ),
        migrations.CreateModel(
            name='Prekladatel',
            fields=[
                ('id_tisk', models.IntegerField(primary_key=True, serialize=False)),
                ('id_osoba', models.IntegerField()),
                ('poradi', models.IntegerField()),
                ('typ', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Překladatel',
                'verbose_name_plural': 'Překladatelé',
                'db_table': 'prekladatel',
            },
        ),
        migrations.CreateModel(
            name='Stavy',
            fields=[
                ('id_stav', models.IntegerField(primary_key=True, serialize=False)),
                ('id_typ', models.IntegerField()),
                ('id_druh', models.IntegerField()),
                ('popis', models.TextField()),
                ('lhuta', models.IntegerField()),
                ('lhuta_where', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Stav',
                'verbose_name_plural': 'Stavy',
                'db_table': 'stavy',
            },
        ),
        migrations.CreateModel(
            name='Tisky',
            fields=[
                ('id_tisk', models.IntegerField(primary_key=True, serialize=False)),
                ('id_druh', models.IntegerField()),
                ('id_stav', models.IntegerField()),
                ('ct', models.IntegerField()),
                ('cislo_za', models.IntegerField()),
                ('id_navrh', models.IntegerField()),
                ('id_org', models.IntegerField()),
                ('id_org_obd', models.IntegerField()),
                ('id_osoba', models.IntegerField()),
                ('navrhovatel', models.TextField()),
                ('nazev_tisku', models.TextField()),
                ('predlozeno', models.TextField()),
                ('rozeslano', models.TextField()),
                ('dal', models.TextField()),
                ('tech_nos_dat', models.IntegerField()),
                ('uplny_nazev_tisku', models.TextField()),
                ('zm_lhuty', models.IntegerField()),
                ('lhuta', models.IntegerField()),
                ('rj', models.IntegerField()),
                ('t_url', models.TextField()),
                ('is_eu', models.IntegerField()),
                ('roz', models.TextField()),
                ('is_sdv', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tisk',
                'verbose_name_plural': 'Tisky',
                'db_table': 'tisky',
            },
        ),
        migrations.CreateModel(
            name='TiskyZa',
            fields=[
                ('id_tisk', models.IntegerField(primary_key=True, serialize=False)),
                ('cislo_za', models.IntegerField()),
                ('id_hist', models.IntegerField()),
                ('id_druh', models.IntegerField()),
                ('nazev_za', models.IntegerField()),
                ('uplny_nazev_za', models.TextField()),
                ('rozeslano', models.DateTimeField()),
                ('id_org', models.IntegerField()),
                ('usn_vybor', models.IntegerField()),
                ('id_posl', models.IntegerField()),
                ('t_url', models.TextField()),
                ('id_vysledek', models.IntegerField()),
                ('cislo_za_post', models.IntegerField()),
                ('sort_it', models.IntegerField()),
                ('roz', models.DateTimeField()),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tisk následný',
                'verbose_name_plural': 'Tisky následující',
                'db_table': 'tisky_za',
            },
        ),
        migrations.CreateModel(
            name='TypAkce',
            fields=[
                ('id_akce', models.IntegerField(primary_key=True, serialize=False)),
                ('popis_akce', models.TextField()),
            ],
            options={
                'verbose_name': 'Typ akce',
                'verbose_name_plural': 'Typy akcí',
                'db_table': 'typ_akce',
            },
        ),
        migrations.CreateModel(
            name='TypFunkce',
            fields=[
                ('id_typ_funkce', models.AutoField(primary_key=True, serialize=False)),
                ('typ_funkce_cz', models.TextField(null=True)),
                ('typ_funkce_en', models.TextField(null=True)),
                ('priorita', models.IntegerField(null=True)),
                ('typ_funkce_obecny', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Typ funkce',
                'verbose_name_plural': 'Typy funkcí',
                'db_table': 'typ_funkce',
            },
        ),
        migrations.CreateModel(
            name='TypInterpelace',
            fields=[
                ('id_typ', models.IntegerField(primary_key=True, serialize=False)),
                ('popis', models.TextField()),
            ],
            options={
                'verbose_name': 'Typ interpelace',
                'verbose_name_plural': 'Typ interpelací',
                'db_table': 'typ_interpelace',
            },
        ),
        migrations.CreateModel(
            name='TypProjednavani',
            fields=[
                ('id_typ', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Typ projednávání',
                'verbose_name_plural': 'Typy projednávání',
                'db_table': 'typ_projednavani',
            },
        ),
        migrations.CreateModel(
            name='TypStavu',
            fields=[
                ('id_typ', models.IntegerField(primary_key=True, serialize=False)),
                ('popis_stavu', models.TextField()),
            ],
            options={
                'verbose_name': 'Typ stavu',
                'verbose_name_plural': 'Typy stavů',
                'db_table': 'typ_stavu',
            },
        ),
        migrations.CreateModel(
            name='TypyProjednavani',
            fields=[
                ('id_typ', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Typ projednávání',
                'verbose_name_plural': 'Typy projednávání',
                'db_table': 'typy_projednavani',
            },
        ),
        migrations.CreateModel(
            name='TypZakon',
            fields=[
                ('id_navrh', models.IntegerField(primary_key=True, serialize=False)),
                ('druh_navrhovatele', models.TextField()),
            ],
            options={
                'verbose_name': 'Typ zákona',
                'verbose_name_plural': 'Typy zákonů',
                'db_table': 'typ_zakon',
            },
        ),
        migrations.CreateModel(
            name='Uitypv',
            fields=[
                ('id_ui_stav', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.TextField(null=True)),
                ('priorita', models.IntegerField()),
            ],
            options={
                'verbose_name': 'UI Typ',
                'verbose_name_plural': 'UI Typy',
                'db_table': 'uitypv',
            },
        ),
        migrations.CreateModel(
            name='Vysledek',
            fields=[
                ('id_vysledek', models.IntegerField(primary_key=True, serialize=False)),
                ('druh_vysledek', models.TextField()),
            ],
            options={
                'verbose_name': 'Výsledek',
                'verbose_name_plural': 'Výsledky',
                'db_table': 'vysledek',
            },
        ),
        migrations.CreateModel(
            name='Bod_schuze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bod', models.IntegerField()),
                ('id_tisk', models.IntegerField(blank=True, null=True)),
                ('bod', models.IntegerField(null=True)),
                ('uplny_naz', models.CharField(blank=True, max_length=255, null=True)),
                ('uplny_kon', models.CharField(blank=True, max_length=255, null=True)),
                ('poznamka', models.CharField(blank=True, max_length=255, null=True)),
                ('pozvanka', models.IntegerField(null=True)),
                ('rj', models.IntegerField(null=True)),
                ('pozn2', models.CharField(blank=True, max_length=255, null=True)),
                ('id_sd', models.IntegerField(blank=True, null=True)),
                ('zkratka', models.CharField(blank=True, max_length=255, null=True)),
                ('id_bod_stav', models.ForeignKey(db_column='id_bod_stav', on_delete=django.db.models.deletion.CASCADE, to='myApp.bod_stav')),
                ('druh_bodu', models.ForeignKey(db_column='id_bodu', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.druh_bodu')),
            ],
            options={
                'verbose_name': 'Bod schůze',
                'verbose_name_plural': 'Body schůze',
                'db_table': 'bod_schuze',
            },
        ),
        migrations.CreateModel(
            name='hl_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('id_h2', models.ForeignKey(db_column='id_h2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hlasovani_h2', to='myApp.hl_hlasovani')),
                ('id_h3', models.ForeignKey(db_column='id_h3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hlasovani_h3', to='myApp.hl_hlasovani')),
                ('id_hlasovani', models.ForeignKey(db_column='id_hlasovani', on_delete=django.db.models.deletion.CASCADE, to='myApp.hl_hlasovani')),
            ],
            options={
                'verbose_name': 'Hlasování kontrola',
                'verbose_name_plural': 'Hlasování kontroly',
                'db_table': 'hl_check',
            },
        ),
        migrations.CreateModel(
            name='hl_vazby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('typ', models.IntegerField()),
                ('id_hlasovani', models.ForeignKey(db_column='id_hlasovani', on_delete=django.db.models.deletion.CASCADE, to='myApp.hl_hlasovani')),
            ],
            options={
                'verbose_name': 'Hlasování vazby',
                'verbose_name_plural': 'Hlasování vazby',
                'db_table': 'hl_vazby',
            },
        ),
        migrations.CreateModel(
            name='Organy',
            fields=[
                ('id_organ', models.IntegerField(primary_key=True, serialize=False)),
                ('zkratka', models.TextField(null=True)),
                ('nazev_organu_cz', models.TextField(null=True)),
                ('nazev_organu_en', models.TextField(null=True)),
                ('od_organ', models.DateField(null=True)),
                ('do_organ', models.DateField(null=True)),
                ('priorita', models.IntegerField(null=True)),
                ('cl_organ_base', models.IntegerField(null=True)),
                ('organ_id_organ', models.ForeignKey(db_column='organ_id_organ', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.organy')),
            ],
            options={
                'verbose_name': 'Orgán',
                'verbose_name_plural': 'Orgány',
                'db_table': 'organy',
            },
        ),
        migrations.CreateModel(
            name='LosInterpelaci',
            fields=[
                ('id_los', models.IntegerField(primary_key=True, serialize=False)),
                ('datum_los', models.DateField(blank=True, null=True)),
                ('typ_los', models.CharField(max_length=1)),
                ('cas_los', models.DateTimeField(null=True)),
                ('schuze', models.IntegerField()),
                ('id_bod', models.ForeignKey(db_column='id_bod', on_delete=django.db.models.deletion.CASCADE, to='myApp.bod_schuze')),
                ('id_org', models.ForeignKey(db_column='id_org', on_delete=django.db.models.deletion.CASCADE, to='myApp.organy')),
            ],
            options={
                'verbose_name': 'Los interpelací',
                'verbose_name_plural': 'Losy interpelací',
                'db_table': 'los_interpelaci',
            },
        ),
        migrations.AddField(
            model_name='hl_hlasovani',
            name='id_organ',
            field=models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.CASCADE, to='myApp.organy'),
        ),
        migrations.CreateModel(
            name='OsobaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField()),
                ('obvod', models.IntegerField()),
                ('strana', models.TextField(null=True)),
                ('id_external', models.IntegerField()),
                ('id_org', models.ForeignKey(db_column='id_org', on_delete=django.db.models.deletion.CASCADE, to='myApp.organy')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.CASCADE, to='myApp.osoby')),
            ],
            options={
                'verbose_name': 'Extra info o osobě',
                'verbose_name_plural': 'Extra info o osobách',
                'db_table': 'osoba_extra',
            },
        ),
        migrations.CreateModel(
            name='hl_zposlanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField()),
                ('id_hlasovani', models.ForeignKey(db_column='id_hlasovani', on_delete=django.db.models.deletion.CASCADE, to='myApp.hl_hlasovani')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.CASCADE, to='myApp.osoby')),
            ],
            options={
                'verbose_name': 'Zpochyb. hlas. poslancem',
                'verbose_name_plural': 'Zpochyb. hlas.poslanci',
                'db_table': 'hl_zposlanec',
            },
        ),
        migrations.CreateModel(
            name='Poradi',
            fields=[
                ('id_poradi', models.IntegerField(primary_key=True, serialize=False)),
                ('vec', models.CharField(max_length=255)),
                ('poradi_l', models.IntegerField(null=True)),
                ('priorita', models.IntegerField(null=True)),
                ('vec32', models.CharField(max_length=255, null=True)),
                ('id_losovani', models.ForeignKey(db_column='id_losovani', on_delete=django.db.models.deletion.CASCADE, to='myApp.losinterpelaci')),
                ('id_ministr', models.ForeignKey(db_column='id_ministr', on_delete=django.db.models.deletion.CASCADE, related_name='ministr_poradi', to='myApp.osoby')),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.CASCADE, related_name='poslanec_poradi', to='myApp.osoby')),
            ],
            options={
                'verbose_name': 'Pořadí',
                'verbose_name_plural': 'Pořadí',
                'db_table': 'poradi',
            },
        ),
        migrations.CreateModel(
            name='Poslanec',
            fields=[
                ('id_poslanec', models.AutoField(primary_key=True, serialize=False)),
                ('id_kraj', models.IntegerField()),
                ('id_kandidatka', models.IntegerField()),
                ('web', models.TextField(null=True)),
                ('ulice', models.TextField(null=True)),
                ('obec', models.TextField(null=True)),
                ('psc', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
                ('telefon', models.TextField(null=True)),
                ('fax', models.TextField(null=True)),
                ('psp_telefon', models.TextField(null=True)),
                ('facebook', models.TextField(null=True)),
                ('foto', models.IntegerField(null=True)),
                ('id_obdobi', models.ForeignKey(db_column='id_obdobi', on_delete=django.db.models.deletion.CASCADE, related_name='poslanci_obdobi', to='myApp.organy')),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.CASCADE, to='myApp.osoby')),
            ],
            options={
                'verbose_name': 'Poslanec',
                'verbose_name_plural': 'Poslanci',
                'db_table': 'poslanec',
            },
        ),
        migrations.CreateModel(
            name='Pkgps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresa', models.TextField()),
                ('sirka', models.CharField(max_length=20)),
                ('delka', models.CharField(max_length=20)),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.CASCADE, to='myApp.poslanec')),
            ],
            options={
                'verbose_name': 'GPS pozice',
                'verbose_name_plural': 'GPS pozice',
                'db_table': 'pkgps',
            },
        ),
        migrations.CreateModel(
            name='omluvy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.DateField()),
                ('od', models.TimeField(blank=True, null=True)),
                ('do', models.TimeField(blank=True, null=True)),
                ('id_organ', models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.CASCADE, to='myApp.organy')),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.CASCADE, to='myApp.poslanec')),
            ],
            options={
                'verbose_name': 'Omluva',
                'verbose_name_plural': 'Omluvy',
                'db_table': 'omluvy',
            },
        ),
        migrations.CreateModel(
            name='hl_poslanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vysledek', models.TextField()),
                ('id_hlasovani', models.ForeignKey(db_column='id_hlasovani', on_delete=django.db.models.deletion.CASCADE, to='myApp.hl_hlasovani')),
                ('id_poslanec', models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.CASCADE, to='myApp.poslanec')),
            ],
            options={
                'verbose_name': 'Hlasování poslance',
                'verbose_name_plural': 'Hlasování poslanců',
                'db_table': 'hl_poslanec',
            },
        ),
        migrations.CreateModel(
            name='Schuze',
            fields=[
                ('id_schuze', models.IntegerField(primary_key=True, serialize=False)),
                ('schuze', models.IntegerField()),
                ('od_schuze', models.DateTimeField()),
                ('do_schuze', models.DateTimeField(blank=True, null=True)),
                ('aktualizace', models.DateTimeField()),
                ('id_org', models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.CASCADE, to='myApp.organy')),
            ],
            options={
                'verbose_name': 'Schůze',
                'verbose_name_plural': 'Schůze',
                'db_table': 'schuze',
            },
        ),
        migrations.AddField(
            model_name='losinterpelaci',
            name='id_schuze',
            field=models.ForeignKey(db_column='id_schuze', on_delete=django.db.models.deletion.CASCADE, to='myApp.schuze'),
        ),
        migrations.AddField(
            model_name='bod_schuze',
            name='id_schuze',
            field=models.ForeignKey(db_column='id_schuze', on_delete=django.db.models.deletion.CASCADE, to='myApp.schuze'),
        ),
        migrations.CreateModel(
            name='Schuze_stav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stav', models.IntegerField()),
                ('typ', models.IntegerField()),
                ('text_dt', models.TextField(null=True)),
                ('text_st', models.TextField(null=True)),
                ('tm_line', models.TextField(null=True)),
                ('id_schuze', models.ForeignKey(db_column='id_schuze', on_delete=django.db.models.deletion.CASCADE, to='myApp.schuze')),
            ],
            options={
                'verbose_name': 'Stav schůze',
                'verbose_name_plural': 'Stavy schůze',
                'db_table': 'schuze_stav',
            },
        ),
        migrations.CreateModel(
            name='Funkce',
            fields=[
                ('id_funkce', models.AutoField(primary_key=True, serialize=False)),
                ('nazev_funkce_cz', models.TextField()),
                ('priorita', models.IntegerField()),
                ('id_organ', models.ForeignKey(db_column='id_organ', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.organy')),
                ('id_typ_funkce', models.ForeignKey(db_column='id_typ_funkce', on_delete=django.db.models.deletion.CASCADE, to='myApp.typfunkce')),
            ],
            options={
                'verbose_name': 'Funkce',
                'verbose_name_plural': 'Funkce',
                'db_table': 'funkce',
            },
        ),
        migrations.CreateModel(
            name='TypOrganu',
            fields=[
                ('id_typ_org', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev_typ_org_cz', models.TextField(null=True)),
                ('nazev_typ_org_en', models.TextField(null=True)),
                ('priorita', models.IntegerField(null=True)),
                ('id_typ_organu', models.ForeignKey(db_column='id_typ_organu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='podrizene_typy', to='myApp.typorganu')),
                ('organ_id_organ', models.ForeignKey(db_column='organ_id_organ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nadrazene_organy', to='myApp.typorganu')),
            ],
            options={
                'verbose_name': 'Typ orgánu',
                'verbose_name_plural': 'Typy orgánů',
                'db_table': 'typ_organu',
            },
        ),
        migrations.AddField(
            model_name='typfunkce',
            name='id_typ_org',
            field=models.ForeignKey(db_column='id_typ_org', on_delete=django.db.models.deletion.CASCADE, to='myApp.typorganu'),
        ),
        migrations.AddField(
            model_name='organy',
            name='id_typ_organu',
            field=models.ForeignKey(db_column='id_typ_organu', on_delete=django.db.models.deletion.CASCADE, to='myApp.typorganu'),
        ),
        migrations.AddField(
            model_name='bod_schuze',
            name='id_typ',
            field=models.ForeignKey(db_column='id_typ', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.typprojednavani'),
        ),
        migrations.CreateModel(
            name='Uistav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steno', models.IntegerField(null=True)),
                ('id_poradi', models.ForeignKey(db_column='id_poradi', on_delete=django.db.models.deletion.CASCADE, to='myApp.poradi')),
                ('id_typ', models.ForeignKey(db_column='id_typ', on_delete=django.db.models.deletion.CASCADE, to='myApp.typinterpelace')),
            ],
            options={
                'verbose_name': 'UI Stav',
                'verbose_name_plural': 'UI Stavy',
                'db_table': 'ui_stav',
            },
        ),
        migrations.CreateModel(
            name='Zarazeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of', models.IntegerField()),
                ('cl_funkce', models.IntegerField()),
                ('od_o', models.DateTimeField()),
                ('do_o', models.DateTimeField(null=True)),
                ('od_f', models.DateField(null=True)),
                ('do_f', models.DateField(null=True)),
                ('id_osoba', models.ForeignKey(db_column='id_osoba', on_delete=django.db.models.deletion.CASCADE, to='myApp.osoby')),
            ],
            options={
                'verbose_name': 'Zařazení',
                'verbose_name_plural': 'Zařazení',
                'db_table': 'zarazeni',
            },
        ),
        migrations.CreateModel(
            name='zmatecne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hlasovani', models.ForeignKey(db_column='id_hlasovani', on_delete=django.db.models.deletion.CASCADE, to='myApp.hl_hlasovani')),
            ],
            options={
                'verbose_name': 'Zmatečné hlasování',
                'verbose_name_plural': 'Zmatečné hlasování',
                'db_table': 'zmatecne',
            },
        ),
    ]
