# Generated by Django 5.0.2 on 2024-02-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druhtisku',
            name='nazev_druh',
            field=models.TextField(null=True),
        ),
    ]
