# Generated by Django 5.0.2 on 2024-02-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_druhtisku_nazev_druh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losinterpelaci',
            name='id_bod',
            field=models.IntegerField(),
        ),
    ]
