# Generated by Django 5.0.2 on 2024-02-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_losinterpelaci_id_bod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losinterpelaci',
            name='cas_los',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
