# Generated by Django 5.0.2 on 2024-02-28 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_losinterpelaci_cas_los'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pkgps',
            name='id',
        ),
        migrations.AlterField(
            model_name='pkgps',
            name='id_poslanec',
            field=models.ForeignKey(db_column='id_poslanec', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.poslanec'),
        ),
    ]
