# Generated by Django 5.0.2 on 2024-02-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_pkgps_id_alter_pkgps_id_poslanec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pkgps',
            name='id_poslanec',
            field=models.OneToOneField(db_column='id_poslanec', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myApp.poslanec'),
        ),
    ]
