# Generated by Django 5.0.2 on 2024-03-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_pkgps_id_poslanec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zarazeni',
            name='id_of',
        ),
        migrations.AddField(
            model_name='zarazeni',
            name='id_funkce',
            field=models.ForeignKey(blank=True, db_column='id_funkce', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.funkce'),
        ),
        migrations.AddField(
            model_name='zarazeni',
            name='id_organ',
            field=models.ForeignKey(blank=True, db_column='id_organ', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.organy'),
        ),
    ]
