# Generated by Django 5.0.2 on 2024-03-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_zarazeni_id_of_zarazeni_id_funkce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zarazeni',
            name='od_o',
            field=models.DateTimeField(null=True),
        ),
    ]
