# Generated by Django 5.0.2 on 2024-03-12 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_alter_zarazeni_od_o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poslanec',
            name='id_kandidatka',
            field=models.ForeignKey(db_column='id_organ', on_delete=django.db.models.deletion.CASCADE, related_name='strana', to='myApp.organy'),
        ),
    ]
