# Generated by Django 5.0.2 on 2024-03-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_poslanec_id_kandidatka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poslanec',
            name='id_obdobi',
            field=models.ForeignKey(blank=True, db_column='id_obdobi', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poslanci_obdobi', to='myApp.organy'),
        ),
    ]
