# Generated by Django 5.0.2 on 2024-03-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_alter_poslanec_id_kandidatka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poslanec',
            name='id_kandidatka',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
