# Generated by Django 5.0.2 on 2024-03-12 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_poslanec_id_kandidatka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poslanec',
            name='id_kandidatka',
            field=models.ForeignKey(db_column='id_kandidatka', null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.organy'),
        ),
    ]
