from django.contrib import admin
from .models.models import *
from .models.models_PaO import *
from .models.models_hl import *
from .models.models_s import *
from .models.models_ui import *
# Register your models here.
admin.site.register(Schuze)
admin.site.register(Bod_schuze)
admin.site.register(TypyProjednavani)
admin.site.register(Bod_stav)
admin.site.register(hl_poslanec)
admin.site.register(omluvy)
admin.site.register(hl_check)
admin.site.register(hl_hlasovani)
admin.site.register(TypFunkce)
admin.site.register(Funkce)
admin.site.register(Organy)
admin.site.register(Zarazeni)
admin.site.register(Poslanec)
admin.site.register(Pkgps)
admin.site.register(OsobaExtra)
admin.site.register(LosInterpelaci)
admin.site.register(Poradi)
admin.site.register(TypZakon)
admin.site.register(DruhTisku)
admin.site.register(TypStavu)
admin.site.register(Stavy)
admin.site.register(TypAkce)
admin.site.register(Tisky)
admin.site.register(Hist)
admin.site.register(HistVybory)
admin.site.register(Vysledek)
admin.site.register(TiskyZa)
admin.site.register(Prekladatel)
admin.site.register(NavrhPodpis)
admin.site.register(Prechody)
admin.site.register(Schuze_stav)
admin.site.register(hl_zposlanec)
admin.site.register(hl_vazby)
admin.site.register(zmatecne)
admin.site.register(TypOrganu)
admin.site.register(Osoby)
admin.site.register(Uitypv)
admin.site.register(Uistav)